services:
  backend:
    build:
      context: ./backend
    container_name: tfm-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    runtime: nvidia  
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - tfm-network

  frontend:
    build:
      context: ./frontend
    container_name: tfm-frontend
    ports:
      - "3000:3000"
    networks:
      - tfm-network

networks:
  tfm-network:
    driver: bridge
